<select id="province">
    <option value="">Choose</option>
    <option value="2" >Abra</option>
    <option value="73" >Agusan del Norte</option>
    <option value="74" >Agusan del Sur</option>
    <option value="40" >Aklan</option>
    <option value="34" >Albay</option>
    <option value="41" >Antique</option>
    <option value="3" >Apayao</option>
    <option value="17" >Aurora</option>
    <option value="78" >Basilan</option>
    <option value="18" >Bataan</option>
    <option value="12" >Batanes</option>
    <option value="26" >Batangas</option>
    <option value="4" >Benguet</option>
    <option value="50" >Biliran</option>
    <option value="46" >Bohol</option>
    <option value="59" >Bukidnon</option>
    <option value="19" >Bulacan</option>
    <option value="13" >Cagayan</option>
    <option value="35" >Camarines Norte</option>
    <option value="36" >Camarines Sur</option>
    <option value="60" >Camiguin</option>
    <option value="42" >Capiz</option>
    <option value="37" >Catanduanes</option>
    <option value="24" >Cavite</option>
    <option value="47" >Cebu</option>
    <option value="64" >Compostela Valley</option>
    <option value="69" >Cotabato</option>
    <option value="65" >Davao del Norte</option>
    <option value="66" >Davao del Sur</option>
    <option value="67" >Davao Occidental</option>
    <option value="68" >Davao Oriental</option>
    <option value="75" >Dinagat Islands</option>
    <option value="51" >Eastern Samar</option>
    <option value="43" >Guimaras</option>
    <option value="5" >Ifugao</option>
    <option value="8" >Ilocos Norte</option>
    <option value="9" >Ilocos Sur</option>
    <option value="44" >Iloilo</option>
    <option value="14" >Isabela</option>
    <option value="6" >Kalinga</option>
    <option value="10" >La Union</option>
    <option value="25" >Laguna</option>
    <option value="61" >Lanao del Norte</option>
    <option value="79" >Lanao del Sur</option>
    <option value="52" >Leyte</option>
    <option value="80" >Maguindanao</option>
    <option value="29" >Marinduque</option>
    <option value="38" >Masbate</option>
    <option value="1" >Metro Manila</option>
    <option value="62" >Misamis Occidental</option>
    <option value="63" >Misamis Oriental</option>
    <option value="7" >Mountain Province</option>
    <option value="45" >Negros Occidental</option>
    <option value="48" >Negros Oriental</option>
    <option value="53" >Northern Samar</option>
    <option value="20" >Nueva Ecija</option>
    <option value="15" >Nueva Vizcaya</option>
    <option value="30" >Occidental Mindoro</option>
    <option value="31" >Oriental Mindoro</option>
    <option value="32" >Palawan</option>
    <option value="21" >Pampanga</option>
    <option value="11" >Pangasinan</option>
    <option value="28" >Quezon</option>
    <option value="16" >Quirino</option>
    <option value="27" >Rizal</option>
    <option value="33" >Romblon</option>
    <option value="54" >Samar</option>
    <option value="70" >Sarangani</option>
    <option value="49" >Siquijor</option>
    <option value="39" >Sorsogon</option>
    <option value="71" >South Cotabato</option>
    <option value="55" >Southern Leyte</option>
    <option value="72" >Sultan Kudarat</option>
    <option value="81" >Sulu</option>
    <option value="76" >Surigao del Norte</option>
    <option value="77" >Surigao del Sur</option>
    <option value="22" >Tarlac</option>
    <option value="82" >Tawi-Tawi</option>
    <option value="23" >Zambales</option>
    <option value="83" >Zamboanga City</option>
    <option value="56" >Zamboanga del Norte</option>
    <option value="57" >Zamboanga del Sur</option>
    <option value="58" >Zamboanga Sibugay</option>
</select>